version: '3.8'

services:
  mongo-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - type: bind
        source: ./mongo
        target: /data/db
    ports:
      - 27018:27017
      
networks:
  epayco: